![NumPy Illustration](https://datascientest.com/en/wp-content/uploads/sites/9/2023/03/illu_numpy_blog-125.png)

> NumPy: The core of Python's scientific computing.



# Introduction to NumPy

NumPy is a fundamental package for scientific computing in Python. It offers support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays.

## Why NumPy?

- <b style="color:blue">Performance</b>: Efficient storage and computation for large data arrays.
- <b style="color:green">Functionality</b>: A broad array of functions to perform complex mathematical operations.
- <b style="color:red">Community</b>: Widely used in scientific computing, data science, and engineering communities.



In [109]:
import numpy as np   # Numpy is often times aliased as "np" 
                     # ("np" also reads : "No Problem" ) 


## Array Creation

Arrays can be created from Python lists, or using built-in NumPy functions:

- From lists: `np.array(aList)`
- Zeros: `np.zeros((nbOfLines, nbOfColumns))`
- Ones: `np.ones((nbOfLines, nbOfColumns))`
- Random: `np.random.random((nbOfLines, nbOfColumns))`


In [110]:
np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

In [111]:
np.zeros((3, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
np.ones((6, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [154]:
A = np.random.random((3, 3)) 
A

array([[0.20610396, 0.81920781, 0.74289204],
       [0.46909914, 0.55282396, 0.05589861],
       [0.74652177, 0.90016407, 0.30565181]])


## Array Indexing and Slicing

Accessing array elements can be done through indexing and slicing:

- Single element: `arr[2, 1]`
- Slice: `arr[:, 1:3]`
- Conditional: `arr[arr > 5]`


In [114]:
A[2]

array([[0.08482685, 0.31125519, 0.42837109],
       [0.98616496, 0.08792581, 0.6049104 ],
       [0.9756917 , 0.71142623, 0.74581299]])

In [115]:
A[2, 1]

array([0.98616496, 0.08792581, 0.6049104 ])

In [116]:
A[2, 1, :-1]

array([0.98616496, 0.08792581])

In [117]:
A[2, 1, 1]

0.08792581280161516

In [118]:
A[::2,::2]

array([[[0.2767105 , 0.92340033, 0.12297031],
        [0.90672583, 0.96025097, 0.50135607]],

       [[0.08482685, 0.31125519, 0.42837109],
        [0.9756917 , 0.71142623, 0.74581299]]])

## Matrix Operations

NumPy provides a wide range of operations that can be performed on arrays, including but not limited to matrix operations, element-wise operations, and statistical operations. Here's an overview of some of the key operations

### Matrix Multiplications

- **Dot Product**: Calculates the dot product of two arrays. For 2-D vectors, it's equivalent to matrix multiplication.
  
  ```a = np.array([[1, 2], [3, 4]])```
  
  ```b = np.array([[5, 6], [7, 8]])```
  
  ```np.dot(a, b)```


In [119]:
a = np.array([[1, 2], [3, 4]])

In [120]:
b = np.array([[5, 6], [7, 8]])

In [121]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

- **Element-wise Multiplication**: Multiplies elements in the same position in two arrays.

In [122]:
a * b


array([[ 5, 12],
       [21, 32]])

- **Element-wise Addition**: Adds elements in the same position in two arrays.

In [123]:
a + b


array([[ 6,  8],
       [10, 12]])

- **Broadcast Addition**: Adds a scalar or an array of compatible shape to another array.

#### Without Numpy :  

In [124]:
L = [[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]]
L

[[1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0]]

In [125]:
L + 4 

TypeError: can only concatenate list (not "int") to list

#### With Numpy 

In [126]:
A = np.ones((5,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [139]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])


## Broadcasting

Broadcasting enables arithmetic operations on arrays of different shapes:

- `a = np.array([1, 2, 3])`
- `b = np.array([[0], [1], [2]])`
- `a + b`


In [140]:
a = np.array([1, 2, 3])

In [141]:
b = np.array([[0], [1], [2]])

In [142]:
a + b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## Transpositions

- **Transpose**: Reverses the dimensions of an array. For a matrix, this means swapping rows and columns. ```a.T```

In [143]:
a 

array([1, 2, 3])

In [144]:
a.T

array([1, 2, 3])

In [145]:
A.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Conjugations

- **Conjugate**: Returns the complex conjugate of all elements in a complex array. ```np.conj(c)```


In [146]:
c = np.array([1+2j, 3+4j])
c

array([1.+2.j, 3.+4.j])

In [147]:
np.conj(c)

array([1.-2.j, 3.-4.j])

## Absolute Values

- **Absolute Value**: Calculates the absolute value of each element in the array.


In [148]:
d = np.array([-1, -2, -3])
d

array([-1, -2, -3])

In [149]:
np.abs(d)

array([1, 2, 3])

## Additional Operations

- **Inverse of a Matrix**: Calculates the multiplicative inverse of a matrix.

In [155]:
np.linalg.inv(A)


array([[-2.29466983, -8.09021917,  7.05680072],
       [ 1.96585963,  9.50694557, -6.51671741],
       [-0.18509691, -8.23906777,  5.22836566]])

- **Determinant of a Matrix**: Calculates the determinant of an array.

In [157]:
np.linalg.det(A)

-0.051708409318409386

- **Eigenvalues and Eigenvectors**: Computes the eigenvalues and right eigenvectors of a square array.

In [159]:
np.linalg.eig(A)

(array([ 1.47653463, -0.48427014,  0.07231524]),
 array([[-0.6336163 , -0.84745876,  0.55397403],
        [-0.36311724,  0.36241547, -0.60709364],
        [-0.68313707,  0.38790293,  0.56969298]]))

- **Solving Linear Equations**: Solves a linear matrix equation, or system of linear scalar equations.

In [162]:
np.linalg.solve(A, b)

array([[ 6.02338227],
       [-3.52648925],
       [ 2.21766355]])


## Basic Operations

NumPy arrays support element-wise arithmetic operations:

- Addition: `a + b`
- Subtraction: `a - b`
- Multiplication: `a * b`
- Division: `a / b`


In [30]:
a = 1
b = 2 

In [31]:
a + b 

3

In [32]:
1 - b 

-1

In [33]:
a * b 

2

In [34]:
a / b 

0.5


## Array Manipulation

Reshaping, splitting, and concatenating arrays:

- Reshape: `np.reshape(a, newshape=(2, 3))`
- Concatenate: `np.concatenate((a1, a2), axis=0)`
- Split: `np.split(a, 3)`


In [35]:
B = np.array((list(range(6))))
B

array([0, 1, 2, 3, 4, 5])

In [36]:
np.reshape(B, newshape=(2, 3))

array([[0, 1, 2],
       [3, 4, 5]])


## Loading and Saving Data

NumPy provides functions to easily load and save data:

- Save: `np.save('my_array', arr)`
- Load: `np.load('my_array.npy')`


In [37]:
np.save('my_array_B', B)


In [38]:
del B 

In [39]:
B

NameError: name 'B' is not defined

In [40]:
 B = np.load('my_array_B.npy')

In [41]:
B

array([0, 1, 2, 3, 4, 5])

![NumPy Illustration](https://thumbs.dreamstime.com/z/d-illustration-red-character-running-faster-than-blue-one-overtaking-competition-concept-114868246.jpg?ct=jpeg)

## Python List vs. NumPy Array Summation

We'll sum ```5.10^7``` numbers using both a Python list and a NumPy array and measure the time it takes for each operation.

First, let's create a Python list and a NumPy array with ```5.10^7```
 random numbers. Then, we'll use the ```%timeit``` magic command in Jupyter to measure the execution time of summing the elements in each case.

In [53]:
import numpy as np
import time

# Creating a large list and a large NumPy array with 1 million elements
n_elements = 5*10**7
large_list = list(range(n_elements))
large_array = np.arange(n_elements)


In [54]:
def sum_python_list(large_list):
    total = 0
    for number in large_list:
        total += number
    return total

%timeit sum_python_list(large_list)


2.32 s ± 57.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
%timeit np.sum(large_array)


18.8 ms ± 295 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
%%time

np.sum(large_array)


CPU times: total: 0 ns
Wall time: 1.85 ms


1642668640

# The END

# Do you have any questions ? 